name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: Thanks for reporting a bug!
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear description of the bug
    validations:
      required: true
  - type: textarea
    id: input
    attributes:
      label: Input
      description: The LaTeX/Typst code that causes the issue
      render: latex
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Output
      description: What you expected to happen
  - type: textarea
    id: actual
    attributes:
      label: Actual Output
      description: What actually happened
  - type: input
    id: version
    attributes:
      label: Version
      description: "Output of `scipen_convert info`"
  - type: dropdown
    id: platform
    attributes:
      label: Platform
      options:
        - Windows
        - macOS
        - Linux
        - WASM/Browser
